[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Social Utility Modeling"
authors = [{name = "Graziella", email = "epgalvan20@g.ucla.edu"}]
dynamic = ["version", "description"]
